### ISSUE TITLE
[Bug] Unable to change schedule of a check

### ISSUE THREAD

**Issue by jdheyburn** [healthchecks/healthchecks#1096]
Hello

Firstly thank you for creating and maintaining this project, I've been using it to monitor my backups at home and its worked wonderfully!

I've encountered a bug where I want to change the schedule of a check from 1 day to 1 week.

![image](https://github.com/user-attachments/assets/481ec676-2cb7-4235-a274-9c27e59700c1)

Clicking it does no action, and in the console there is this error:

```
Uncaught TypeError: $(...).selectpicker is not a function
    <anonymous> https://DOMAIN/static/CACHE/js/output.44d76dd76ae9.js:3
    dispatch https://DOMAIN/static/CACHE/js/output.85076f027d3b.js:1
    handle https://DOMAIN/static/CACHE/js/output.85076f027d3b.js:1
output.44d76dd76ae9.js:3:647
    <anonymous> https://DOMAIN/static/CACHE/js/output.44d76dd76ae9.js:3
    dispatch https://DOMAIN/static/CACHE/js/output.85076f027d3b.js:1
    handle https://DOMAIN/static/CACHE/js/output.85076f027d3b.js:1

```

I am running v3.7. Would appreciate any help, thanks!

**Comment by cuu508** [comment]
Thanks for the report.

How does your hosting setup look like? Are you using the Healthchecks docker image or not? If not, did you run `manage.py collectstatic` and `manage.py compress` after upgrading to v3.7?

**Comment by jdheyburn** [comment]
I'm running it on NixOS and not via Docker, those steps you mentioned are included in the systemd preStart hook:

https://github.com/NixOS/nixpkgs/blob/55d15ad12a74eb7d4646254e13638ad0c4128776/nixos/modules/services/web-apps/healthchecks.nix#L225-L228

I also had the same problem when I was on 3.6, I upgraded to the latest version to see if that would fix it. I can revert back to 3.6 easily enough to test it there too if that helps.

**Comment by jdheyburn** [comment]
Actually I've cleared the `static` directory so that all the static files get rebuilt, and that has fixed it. I think something about my setup must've got it in a bad state. Appreciate your time and effort on this!
